-------------------------------------------------------------------------------
-- Title      : Components package (generated by Emacs VHDL Mode 3.33.6)
-- Project    : 
-------------------------------------------------------------------------------
-- File       : components.vhd
-- Author     : Calle  <calle@Alukiste>
-- Company    : 
-- Created    : 2012-02-12
-- Last update: 2012-02-12
-- Platform   : 
-- Standard   : VHDL'87
-------------------------------------------------------------------------------
-- Description: 
-------------------------------------------------------------------------------
-- Copyright (c) 2012 
-------------------------------------------------------------------------------
-- Revisions  :
-- Date        Version  Author  Description
-- 2012-02-12  1.0      calle   Created
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-------------------------------------------------------------------------------

package adc_mcp3008_pkg is


  type adc_mcp3008_spi_out_type is record
    mosi : std_logic;
    cs_n : std_logic;
    sck  : std_logic;
  end record;

  type adc_mcp3008_spi_in_type is record
    miso : std_logic;
  end record;

  -----------------------------------------------------------------------------
  -- Component declarations
  -----------------------------------------------------------------------------
  component adc_mcp3008
    generic (
      DELAY : natural);
    port (
      adc_out    : out adc_mcp3008_spi_out_type;
      adc_in     : in  adc_mcp3008_spi_in_type;
      start_p    : in  std_logic;
      adc_mode_p : in  std_logic;
      channel_p  : in  std_logic_vector(2 downto 0);
      value_p    : out std_logic_vector(9 downto 0);
      done_p     : out std_logic;
      reset      : in  std_logic;
      clk        : in  std_logic);
  end component;

  --component adc_mcp3008
  --  generic (
  --    DELAY : natural);
  --  port (
  --    miso_p     : in  std_logic;
  --    mosi_p     : out std_logic;
  --    cs_np      : out std_logic;
  --    sck_p      : out std_logic;
  --    start_p    : in  std_logic;
  --    adc_mode_p : in  std_logic;
  --    channel_p  : in  std_logic_vector(2 downto 0);
  --    value_p    : out std_logic_vector(9 downto 0);
  --    done_p     : out std_logic;
  --    reset      : in  std_logic;
  --    clk        : in  std_logic);
  --end component;

  --component adc_mcp3008_tb
  --end component;

end adc_mcp3008_pkg;

-------------------------------------------------------------------------------
