-------------------------------------------------------------------------------
-- Title      : Components package (generated by Emacs VHDL Mode 3.33.6)
-- Project    : 
-------------------------------------------------------------------------------
-- File       : components.vhd
-- Author     : Calle  <calle@Alukiste>
-- Company    : 
-- Created    : 2012-03-11
-- Last update: 2012-04-15
-- Platform   : 
-- Standard   : VHDL'87
-------------------------------------------------------------------------------
-- Description: 
-------------------------------------------------------------------------------
-- Copyright (c) 2012 
-------------------------------------------------------------------------------
-- Revisions  :
-- Date        Version  Author  Description
-- 2012-03-11  1.0      calle   Created
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

library work;
use work.bus_pkg.all;
--use work.reg_file_pkg.all;
--use work.utils_pkg.all;

-------------------------------------------------------------------------------

package reg_file_pkg is

   type reg_file_type is array (natural range <>) of std_logic_vector(15 downto 0);

   -----------------------------------------------------------------------------
   -- Component declarations
   -----------------------------------------------------------------------------

   component reg_file
      generic (
         BASE_ADDRESS : integer range 0 to 32767;
         REG_ADDR_BIT : natural);
      port (
         bus_o : out busdevice_out_type;
         bus_i : in  busdevice_in_type;
         reg_o : out reg_file_type;
         reg_i : in  reg_file_type;
         reset : in  std_logic;
         clk   : in  std_logic);
   end component;

end reg_file_pkg;

-------------------------------------------------------------------------------
