-------------------------------------------------------------------------------
-- Title      : Components package (generated by Emacs VHDL Mode 3.33.6)
-- Project    : Loa
-------------------------------------------------------------------------------
-- Standard   : VHDL'87
-------------------------------------------------------------------------------
-- Description: 
-------------------------------------------------------------------------------
-- Copyright (c) 2013 
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.bus_pkg.all;

-------------------------------------------------------------------------------

package adc_ad7266_pkg is

   -- The Analog Device AD7266 is a 12-Bit ADC with 12 single ended or 6 differential
   -- channels
   type adc_ad7266_values_type is array (natural range <>) of std_logic_vector(11 downto 0);

   type adc_ad7266_spi_out_type is record
      cs_n     : std_logic;
      sck      : std_logic;
      a        : std_logic_vector(2 downto 0);
      sgl_diff : std_logic;
   end record;

   type adc_ad7266_spi_in_type is record
      d_a : std_logic;
      d_b : std_logic;
   end record;

   -----------------------------------------------------------------------------
   -- Component declarations
   -----------------------------------------------------------------------------
   component adc_ad7266_single_ended
      generic (
         DELAY : natural);
      port (
         -- signals to and from real hardware
         adc_out : out adc_ad7266_spi_out_type;
         adc_in  : in  adc_ad7266_spi_in_type;

         -- signals to and from other logic in FPGA
         start_p    : in  std_logic;
         adc_mode_p : in  std_logic;
         channel_p  : in  std_logic_vector(2 downto 0);
         value_a_p  : out std_logic_vector(11 downto 0);
         value_b_p  : out std_logic_vector(11 downto 0);
         done_p     : out std_logic;
         clk        : in  std_logic);
   end component;


   component adc_ad7266_single_ended_module
      generic (
         BASE_ADDRESS : integer range 0 to 16#7FFF#;
         CHANNELS : positive);
      port (
         adc_out_p    : out adc_ad7266_spi_out_type;
         adc_in_p     : in  adc_ad7266_spi_in_type;
         bus_o        : out busdevice_out_type;
         bus_i        : in  busdevice_in_type;
         adc_values_o : out adc_ad7266_values_type(11 downto 0);
         clk          : in  std_logic);
   end component;

end adc_ad7266_pkg;

-------------------------------------------------------------------------------
